In [35]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.dummy import DummyClassifier # mô hình cơ sỏ

In [36]:
import sys
import os
import pandas as pd
import numpy as np

In [37]:
sys.path.append(os.path.abspath(os.path.join('..', 'utils')))

# Lấy thư mục hiện tại
current_directory = os.getcwd()
folder_path1 = os.path.join(current_directory,'../../data/train_test')

In [38]:
x = pd.read_csv(f'{folder_path1}/xtrain_data.csv')
y = pd.read_csv(f'{folder_path1}/xtest_data.csv')
z = pd.read_csv(f'{folder_path1}/ytrain_data.csv')
t = pd.read_csv(f'{folder_path1}/ytest_data.csv')

x_train = x.iloc[:, 1:].values
x_test = y.iloc[:, 1:].values

y_train = z['drop_out'].values
y_test = t['drop_out'].values


In [55]:
x_train 

array([[ 2.20000984e+09, -5.66955714e-01, -2.12403621e-02],
       [ 1.92810208e+09,  7.58444164e-02,  1.46794850e-01],
       [ 1.93413563e+09,  1.02466137e+00, -3.07762830e-01],
       ...,
       [ 2.00000101e+09, -8.30839818e-01, -1.78977038e-01],
       [ 1.96713771e+09,  1.28207846e+00, -4.03131065e-01],
       [ 1.93682015e+09,  5.16510725e-01,  2.50851194e-01]])

In [56]:
x_test

array([[ 2.10100084e+09,  5.53320482e-02,  1.46794850e-01],
       [ 1.90868157e+09,  2.80766856e-01,  5.17795166e-01],
       [ 2.02977581e+09,  1.30038730e+00, -3.53087741e-01],
       [ 2.11748148e+09,  1.06761440e+00, -1.56031701e-01],
       [ 2.20000842e+09, -7.21544039e-01, -2.58865324e-01],
       [ 2.00000099e+09,  8.49663642e-01, -1.66239462e-01],
       [ 2.00000153e+09, -8.07895905e-01, -9.83539099e-02],
       [ 2.20000724e+09, -9.07617098e-01, -1.30068529e-01],
       [ 2.11958549e+09,  2.09166979e-01,  5.94410630e-01],
       [ 1.94142688e+09,  1.01321650e+00, -2.96721123e-01],
       [ 1.94089978e+09,  1.01404389e+00, -2.97519363e-01],
       [ 2.10814120e+09,  3.61466180e-01,  4.61427637e-01],
       [ 2.02980564e+09,  3.13725689e-01,  3.94904645e-01],
       [ 2.20000678e+09, -5.29513803e-01,  2.83013515e-01],
       [ 2.19612581e+09,  8.30667488e-01,  3.28916308e-02],
       [ 2.20001124e+09, -8.06040673e-01, -1.46519112e-01],
       [ 1.95015542e+09,  9.99515587e-01

In [57]:
y_train

array([0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 1.

In [58]:
y_test

array([1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 1.])

In [39]:
nb_model = GaussianNB()

In [40]:
# Chuyển đổi y_train thành nhãn phân loại.
y_train_class = np.where(y_train >= 0.5, 1, 0)
y_test_class = np.where(y_test >= 0.5, 1, 0)

In [41]:
nb_model.fit(x_train, y_train_class)

GaussianNB()

In [42]:
y_pred_nb = nb_model.predict(x_test)

In [43]:
y_pred_nb

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1])

In [44]:
accuracy = accuracy_score(y_test_class, y_pred_nb)
conf_matrix = confusion_matrix(y_test_class, y_pred_nb)
class_report = classification_report(y_test_class, y_pred_nb)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)


Accuracy: 0.7936507936507936
Confusion Matrix:
[[48 15]
 [11 52]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.76      0.79        63
           1       0.78      0.83      0.80        63

    accuracy                           0.79       126
   macro avg       0.79      0.79      0.79       126
weighted avg       0.79      0.79      0.79       126



In [45]:
dummy_clf = DummyClassifier(strategy="most_frequent")
dummy_clf.fit(x_train, y_train)
baseline_prediction = dummy_clf.predict(x_test)
baseline_accuracy = accuracy_score(y_test_class, np.where(baseline_prediction==np.unique(baseline_prediction)[0],0,baseline_prediction))

In [46]:
print("Model accuracy:", accuracy)
print("Baseline accuracy:", baseline_accuracy)

Model accuracy: 0.7936507936507936
Baseline accuracy: 0.5


In [47]:
# [[48 15]
#  [11 52]]


'''
TP: 48, TN: 52, FP: 15, FN: 11
'''

'\nTP: 48, TN: 52, FP: 15, FN: 11\n'

In [48]:
x_test.shape[0]

126

In [49]:
# Số lượng các mẫu trong tập dữ liệu kiểm tra (test set)
N = x_test.shape[0]

# Độ chính xác toàn thể (Overall Accuracy): (TN + TP) / N
overall_accuracy = round((48 + 52) / N * 100, 2)
print("Độ chính xác toàn thể: ", overall_accuracy)

# Sai số toàn thể (Overall Mistake): (FP + FN) / N
overall_mistake = round((15 + 11) / N * 100, 2)
print("Sai số toàn thể: ", overall_mistake)

# Độ nhạy (Sensitivity): TP / (TP + FN)
sensitivity = round((48 / (48 + 11)) * 100, 2)
print("Độ nhạy: ", sensitivity)

# Sai số của dự đoán sinh viên thôi học (Mistake Rate for Dropout Prediction)
mistake = round(100 - sensitivity, 2)
print("Tỉ lệ mô hình dự đoán sai sinh viên nghỉ học: ", mistake)

# Độ đặc hiệu (Specificity): TN / (TN + FP)
specificity = round((52 / (52 + 15)) * 100, 2)
print("Độ đặc hiệu: ", specificity)

# Sai số tỉ lệ mô hình dự đoán chính xác sinh viên không thôi học (Mistake Rate for Retention Prediction)
mistake_specificity = round(100 - specificity, 2)
print("Sai số tỉ lệ mô hình dự đoán chính xác sinh viên không thôi học: ", mistake_specificity)


Độ chính xác toàn thể:  79.37
Sai số toàn thể:  20.63
Độ nhạy:  81.36
Tỉ lệ mô hình dự đoán sai sinh viên nghỉ học:  18.64
Độ đặc hiệu:  77.61
Sai số tỉ lệ mô hình dự đoán chính xác sinh viên không thôi học:  22.39


In [50]:
student_id = y.iloc[:, 1]
df_pred = pd.concat([student_id,pd.DataFrame(y_test_class)], axis = 1).rename(columns = {0: 'drop_out'})
df_pred.rename(columns = {0: 'drop_out'}, inplace=True)

In [51]:
df_pred[df_pred['drop_out']==1]

student_id  drop_out
0    2101000840         1
1    1908681570         1
2    2029775814         1
3    2117481481         1
5    2000000986         1
..          ...       ...
114  2056618677         1
115  2000004787         1
117  2063054317         1
122  2000000487         1
125  2000004424         1

[63 rows x 2 columns]

In [52]:
### Dự đoán đúng.

In [59]:
from statsmodels.stats.proportion import proportion_confint # Tính khoảng tin cậy
lower_bound, upper_bound = proportion_confint(sum(y_pred_nb), len(y_pred_nb), alpha=0.05, method='wilson')
print(f'lower_bound: {lower_bound: .4f}' )
print(f'upper_bound: {upper_bound: .4f}' )

lower_bound:  0.4450
upper_bound:  0.6166


In [54]:
class_report = classification_report(y_test_class, y_pred_nb, output_dict=True)
df_class_report_df = pd.DataFrame(class_report)
df_class_report_df.to_csv('../visualization/data/native_bayes.csv')